#!/bin/sh

if [ -f .orglatexbeamer-portable ] ; then
   echo "Execute this script in directory where your documents are."
   echo "(not in orglatexbeamer-portable directory)"
   exit 1
fi

dir=$(dirname $0)

echo "directory of orglatexbeamer-portable: $dir"
read -p "confirm [Y/n] ?" reply
case $reply in
     Y|y) ;;
     *) echo "not confirmed, exiting."; exit 0;;
esac

echo "Creating template configuration..."
ln -sf $dir/emacs .emacs.d
ln -sf $dir/make .make
touch Makefile

echo "Creating standard Makefile..."
cat >> Makefile << "EOF" # quote delimiter to avoid expansion, cmd subst, ...
default: all

# Documents (article)
D_ORG=$(wildcard *.org)

# Presentations (beamer)
B_ORG=

%.pdf: %.org
	$(org_article_to_pdf)
%.html: %.org
	$(org_article_to_html)

include .make/Makefile.inc
EOF

echo "Copying template files..."
cp $dir/org.css .
